all:
    # install pycocotools locally
	/BS/eldar/work/software/python3_tf_0.12rc1/bin/python setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	/BS/eldar/work/software/python3_tf_0.12rc1/bin/python setup.py build_ext install
	rm -rf build